[build]
  publish = "."
  command = "pip install -r requirements.txt"
  
[build.environment]
  PYTHON_VERSION = "3.11"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "python app.py"
  port = 5000

[context.production.environment]
  NODE_ENV = "production"
